; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Tue Jan 19 2021 17:25:01 GMT+0800 (中国标准时间)

M83            ; relative extruder moves
G1 E-3 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
;G1 H2 X2 U269 F6000 ; go to X=0 Y=0
G28 X U ; home the X and U carriages


M118 P2 S"//action::paused"


