; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.10+4-LPC on Tue Jan 19 2021 17:25:01 GMT+0800 (中国标准时间)

M83 ; relative extruder movement
G1 E-2 F3600 ; retract 2mm
M106 S0           ; turn off our print cooling fan
;G91 ; relative axis movement
;G1 Z3 F500 ; up 3mm
G90 ; absolute axis movement
G1 H1 X2 F6000 ; park the X carriage at -48mm -- use S2 with RRF 2.01 and earlier

;G90 ; absolute axis movement
;G28 X ; home the X and U carriages